server.port=8074

spring.application.name=items-services
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ms_items}
spring.datasource.username=rhworks
spring.datasource.password=s3cr3t
spring.datasource.driver-class-name=org.postgresql.Driver
