server.port=8071

spring.application.name=orders-services
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3216/ms_orders}
spring.datasource.username=rhworks
spring.datasource.password=s3cr3t

