server.port=8084

spring.application.name=storage-services
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ms_storage}
spring.datasource.username=rhworks
spring.datasource.password=s3cr3t

